### ISSUE TITLE
Error

### ISSUE THREAD

**Issue by JHill29th** [overfl0/Bulletproof-Arma-Launcher#192]
```An error occurred in a subprocess:
Build: 1852491163dee9dbfd5efa5ca54451d1c80fb9ac
Traceback (most recent call last):
  File "process.py", line 332, in _protected_call
  File "sync\preparer.py", line 253, in prepare_all
  File "sync\preparer.py", line 235, in run
  File "sync\preparer.py", line 59, in handle_messages
  File "sync\preparer.py", line 121, in on_mod_reuse_message
  File "sync\torrent_utils.py", line 309, in symlink_mod
WindowsError: [Error 145] The directory is not empty: u'C:\\Users\\HILL\\Documents\\Arma 3\\Frontline_Launcher\\@CUP_Kunduz'```

**Comment by overfl0** [comment]
Have you done anything to `C:\\Users\\HILL\\Documents\\Arma 3\\Frontline_Launcher\\@CUP_Kunduz` manually before starting the launcher (or after starting it)?

By manually, I mean in the file explorer. Anything **not** inside the launcher.

A quick workaround would be to delete that folder and restart the launcher.

**Comment by overfl0** [comment]
It looks like you started the launcher, clicked INSTALL, then was presented with the "find/reuse" mods message.
Then you copied manually the CUP_Kunduz directory in your file system.
Then you clicked "Use this mod" for CUP_Kunduz (in the launcher) or you selected a directory for CUP_Kunduz by clicking te directory icon (also in the launcher).

Is this what happened?

**Comment by JHill29th** [comment]
I (wrongly) assumed the new `@CUP_Kunduz` would be mostly the same data as `@Kunduz Afghanistan`.
I copied the folder `@Kunduz Afghanistan` and renamed it `@CUP_Kunduz` then started the launcher and told it to install.

**Comment by overfl0** [comment]
`I copied the folder @Kunduz Afghanistan and renamed it @CUP_Kunduz then started the launcher and told it to install.`
This is, simply put, impossible. From the stacktrace you gave me:
`File "sync\preparer.py", line 121, in on_mod_reuse_message`

You wouldn't get the `reuse_message` request for `@CUP_Kunduz` if that folder was already present in the filesystem the moment you clicked INSTALL. You can only get that message for missing directories.

So you must have clicked INSTALL first and then, while you had a for directory selection, you must have copied the files *after the launcher got the information about what is and what is not missing*.

Anyway, since you have fixed your problem, I'm closing the issue.
