### ISSUE TITLE
[Close]Help me please!

### ISSUE THREAD

**Issue by cshard447** [overfl0/Bulletproof-Arma-Launcher#198]
I have created a configuration file written in the WIKI, but I still do not get an update for the creation of mods
My server host
OC: Windows server 2012 R2
Web Server: OpenServer 5.2.6
FTP Server: FileZilla Server last version
Ram: 2gb
disk storage: 40gb
--sorry for my bad english
devmode.conf
![screenshot_1](https://cloud.githubusercontent.com/assets/7473900/23102671/b53c6b1e-f6be-11e6-9eb6-88acb0fcc6fa.png)
error
![screenshot_2](https://cloud.githubusercontent.com/assets/7473900/23102768/63885790-f6c0-11e6-8b34-1bcf1d733fcb.png)

server file structure
![screenshot_3](https://cloud.githubusercontent.com/assets/7473900/23102769/67cf9f16-f6c0-11e6-9db2-ba585daa8262.png)

**Comment by overfl0** [comment]
Hey!

It's quite hard to say what your problem is from this description, because I don't have access to your configuration file, only the `devmode.conf` file but I can already tell you that you are not supposed to uncomment the values that are above the "create_torrents" value.
They are for debugging purposes only.

See: https://github.com/overfl0/Bulletproof-Arma-Launcher/blob/next/devmode_sample.conf#L26

You should have set the right values in `launcher_configuration.py`, first. I've just noticed that the values in there are a little old and I should update them. See: https://github.com/overfl0/Bulletproof-Arma-Launcher/blob/next/resources/frontline/launcher_configuration.py for an up date file.

I mean, they are correct and will work, but the old file suggests making some additional directories in the path that just complicates stuff. I suggest you put your `metadata.json` directly in your base http directory for example (and set the path to `metadata_path = '/metadata.json'`) and skip the "/updater" directory since you have a separate domain already set up (launcher.kuban-arma3.tk)

Also I might make a small update in a few hours with some (small) changes to uploading the mods so keep an eye on `devmode_sample.conf` changes. Those changes will be in response to some requests of other people that have tried to create their own laucher.

**Comment by cshard447** [comment]
launcher_configuration
![image](https://cloud.githubusercontent.com/assets/7473900/23104257/43004526-f6db-11e6-8af4-fd6d278a3807.png)

devmode.conf
![image](https://cloud.githubusercontent.com/assets/7473900/23104265/663e9a1a-f6db-11e6-8385-53f3e3467b02.png)

server file structure
![image](https://cloud.githubusercontent.com/assets/7473900/23104272/9e098a9a-f6db-11e6-9f6d-d55d0a6771c8.png)

I have done all that you have described ..
![image](https://cloud.githubusercontent.com/assets/7473900/23104286/cd5485c0-f6db-11e6-8cdd-f434692dd0ed.png)

**Comment by overfl0** [comment]
Hey!

I removed your screenshot because you had your password written in there. Next time just copy-paste text :).

As for the issue, you can pass `metadata.json` to a json validator which I did for you and it said that you have a superfluous comma (",") after "teamspeak". In JSON you can't have: `... "something", }`.

I'm sorry but I can't help you much more than this today as I'm trying to put a new version of the launcher in an hour. I've already made some changes in the code because of your issues.
I'll update the wiki with workarounds as soon as I find the time to do that.

**Comment by cshard447** [comment]
Thank you, I apologize for my carelessness!

**Comment by overfl0** [comment]
Quick note: add this to your devmode.conf to stay compatible with new versions:
`"#server_metadata_filename": "metadata.json", "#(Optional)": "",`

Releasing in a few minutes, hopefully...

**Comment by cshard447** [comment]
You can remove the check on Steam?
to run pirated versions of the game
Thanks :)

**Comment by overfl0** [comment]
Lol!

No.
