### ISSUE TITLE
Force update while seeding if new verison uploaded.

### ISSUE THREAD

**Issue by Schadler17** [overfl0/Bulletproof-Arma-Launcher#213]
While seeding, also check for updates every 10-20 seconds or so incase last minute updates are applied or something while you're seeding. Would prevent issues with people seeding non-updated versions of the game. Could just detect the updated version and install automatically, then continue seeding.

**Comment by overfl0** [comment]
I was rather thinking about a check every 10 minutes, maybe 5 but not much less.

I don't want the launcher to hammer out the server. Besides, the last-minute change are not going to happen that often - especially later, when there will not be a need for events anymore, but everyone will be playing 24/7 (hopefully this happens soon :D).

I'm making some work right now that is theoretically unrelated, because it applies to updating mods, but it will probably pave the way for automatic starting of the downloads.

**Comment by Schadler17** [comment]
Very nice, looking forward to that very much so.
In the event we get auto-updates from the server, I'll leave my launcher up 24/7 to seed continuously. :>
