### ISSUE TITLE
Request: Display current Frontline mod version

### ISSUE THREAD

**Issue by ballista-milsim** [overfl0/Bulletproof-Arma-Launcher#230]
I see change log for 1.0.1.0 saying the bug I'm about to report is fixed. How do I know if I'm playing 1.0.1.0 or previous version?

**Comment by overfl0** [comment]
See the top right corner of the launcher :)

![2017-05-02_23h25_52](https://cloud.githubusercontent.com/assets/1450333/25640120/b49413fc-2f8e-11e7-9429-60e200f5c051.png)

You should always be using the latest version since they autoupdate (except when I push some Frontline-related quickfixes that don't warrant making a full release for the launcher yet).
In other words, an amendment: your launcher will probably always be at the latest version seen in the Releases page, or in some cases, even newer).

https://github.com/overfl0/Bulletproof-Arma-Launcher/releases

**Comment by ballista-milsim** [comment]
I was talking about the mod itself. Not the launcher. How do I know version of the mod given this numbers?

**Comment by overfl0** [comment]
Err... but this is the github for the launcher, which can be used with mods other than Frontline. TacBF also uses it.

You are better asking the developers of that mod ;).

Okay, I'm joking! The Frontline version should be shown in the Menu screen of Arma, AFAIR. Either connect with the launcher and then esc->disconnect or just select "no server" in the launcher.

**Comment by ballista-milsim** [comment]
Makes sense. However, I think the launcher itself could have such a feature like reading mod version from somewhere (you have to configure launcher for your mod somehow, right?) and even have a link/button "Report bug" that leads to issue tracker (again configurable in the launcher by launcher admin). This could make reporting issues easier. You don't have to reopen if it's not planned, I just wanted to give more details of what I was initially requesting
