### ISSUE TITLE
Allow not running BattlEye when just running Arma (no server)

### ISSUE THREAD

**Issue by jonpas** [overfl0/Bulletproof-Arma-Launcher#256]
I'd even argue that should be the default (no BattlEye), but a switch would be nice. Maybe even a configurable one through `metadata.json`, like a global `"battleye": false`.

**Comment by overfl0** [comment]
Honestly, I was seriously considering removing the "just run Arma" button because:

1) Its low utility - I'm not sure anyone ever uses it
2) It's really problematic if you have 2 servers and a base set of mods applied globally + at least one custom mod per server. This way, when you "just run arma", the mods applied will be just the base mods, resulting in you being unable to actually connect to either server.

It would make much sense to remove that button and somehow add an option or a special way of clicking (ctrl+click? click+hold? special mini button?) to run the game with the exact set of mods for a given server but without connecting to it.
Also, the question is whether this will ever be needed by non-devs. If not, then it can be hidden somewhere in the devmode menu.

Loosely related: https://github.com/overfl0/Bulletproof-Arma-Launcher/issues/251

**Comment by jonpas** [comment]
When I get a bug reported and require a classname or similar, I usually tell whoever reported it if he can just launch our modpack and get the info, without connecting to the server. I think that button is useful. But I do agree that it is not as useful in the scenario you described, because it would not be the same set of mods and therefore bug not reproducible.

I like how vanilla launcher does a similar thing, it has an arrow next to the button that shows the drop-down to "Play without mods" (of course Bulletproof one would have appropriate text). If going for 2 buttons, it might be clearer to name them "Join" and "Launch" or something similar.

As of why I opened this issue: we don't use BattlEye on our servers, and many communities also don't on their private servers. So when you want to test something or get information from someone (as said above) you are greeted with the BattlEye message (first time) and possibly not able to run it, because BattlEye servers are down and block X dll.

**Comment by overfl0** [comment]
Regarding the battleye setting, this is the commit that allowed running with BE to be customizable at all: https://github.com/overfl0/Bulletproof-Arma-Launcher/commit/fe8745eb63670c99c81c6d3af5a7f72a533d708b

This could be expanded to use a global option, besides what's ser up per-server, probably. Currently, it's ON by default, and  "just run Arma" uses those defaults.

---

Regarding additional options, there once was an additional button with 3 horizontal lines (|||) that meant "more options", just right of the "PLAY" text. Clicking on it opened a popup where you could previously select a server.
It has been removed with this commit: https://github.com/overfl0/Bulletproof-Arma-Launcher/commit/32f6e835e3cdf307c52cc0849e48eaf37f17861a

I'm thinking that it may probably be added again but clicking on it would allow you to select some options like:
- Connect with BattlEye enabled
- Connect with BattlEye disabled
- Just run Arma with the mods for this server
- Same as above but with BE enabled / disabled

The best thing, I think would be to have buttons scrolling up from the bottom, instead of a popup, but that would require more work than just roughly reverting the commit.

**Comment by jonpas** [comment]
I really really like both of those ideas!

**Comment by jonpas** [comment]
With global BattlEye setting it makes no sense to have "Connect with BattlEye enabled/disabled" anymore, except for when no server is selected, so we'd end up with:
- Just run Arma with the mods for this server (with BattlEye)
- Just run Arma with the mods for this server (without BattlEye)
- Play without installing (devmode-only) https://github.com/overfl0/Bulletproof-Arma-Launcher/issues/251#issuecomment-342991495

(Preferably shorter names.)

#263 will close this, as it solves the original issue, I will open a new issue for the drop-up.
