### ISSUE TITLE
Hide text "Uploading: 0 connections..." when there's no uploading going on

### ISSUE THREAD

**Issue by Leondor777** [overfl0/Bulletproof-Arma-Launcher#271]

**Comment by overfl0** [comment]
You still need a notification that something is indeed happening IMO.

**Comment by Leondor777** [comment]
Huh? I mean when nothing is happening.

**Comment by overfl0** [comment]
But you're connected to the tracker (periodically updating the stats), listening to new incoming data requests and if anyone comes you will start uploading your data. Also, a second (bittorrent) process is running in the background during all this time.

If you set seeding to "Never", then you can say that literally nothing is happening.

I want the user to know that seeding is currently enabled so that the launcher won't "start uploading data all of the sudden, by itself".

**Comment by Leondor777** [comment]
then show the text "Ready to seed"
