### ISSUE TITLE
Documentation for Launcher Authentication

### ISSUE THREAD

**Issue by JudahHarvey** [overfl0/Bulletproof-Arma-Launcher#283]
I would like to use the launcher authentication function to enable a wider distribution of my build of it into the public. But I can't find any documentation for how to set a password or how to hide any servers or functionality behind the login. Is there anywhere I could see an example of a working authentication setup?

**Comment by overfl0** [comment]
Hey,

It's something that's not documented on purpose because what we're currently using is a half-baked, badly done implementation :). Feel free to implement your own!

Basically, for now, you point the launcher to a hidden file (NOT served by the webserver) that looks just like metadata.json, but has an additional `"hidden_servers": [ ... ]` entry. The launcher will treat those entries just like regular server entries, *while updating the mods*.

Then, you create a php (or python, whatever...) script that fires whenever someone requests metadata.json serves a "fake" metadata.json with the `hidden_servers` entries stripped if the user didn't authenticate using basic_auth or appends its contents to the `servers`, if the user did authenticate using basic_auth.

It's something that I always wanted to implement in a 2.0 version, with better mod management, etc... but ended up leaving it as is because of the lack of interest for it (AFAIK we're the only group using that feature)
